### ISSUE TITLE
How to count the number of zeros in BF? 

### ISSUE THREAD

**Issue by AaronRanAn** [axiak/pybloomfiltermmap#92]
How do I count the number of zeros (thus ones) in the bloom filter? Is there any existing method/attribute I can use or do I have to treat it as a bit array and go from there?

**Comment by mizvyt** [comment]
I have tried and it seems to be possible to include the bit vector as a property for `BloomFilter`.
You just need to include `unsigned int * vector` in the `cbloomfilter.pxd` file, like this (line 6):
```
ctypedef struct MBArray:
    long bits
    long size
    char * filename
    unsigned int * vector
    int fd
```
.. and then add the vector as a property in `pybloomfilter.pyx`:
```
// At the top of imports
from libc.stdint cimport uintptr_t
...
property bit_array:
    def __get__(self):
        self._assert_open()
        return <uintptr_t>self._bf.array.vector
```
This will give you the vector as an integer. You should be able to do bitwise operations from here.

I'm unsure what would be the impact if the bloom filter size is very large, though. Not sure if I would like to access raw data like that in the case of millions of items.

Btw, I'm contributing to the following repo (the Python 3 version of pybloomfiltermmap):
https://github.com/prashnts/pybloomfiltermmap3
I suggest you follow updates there (as much as there may be at this point).

**Comment by AaronRanAn** [comment]
Thanks a lot @mizvyt! I will try it out. 

I actually would prefer to use pybloomfiltermmap3. If the development team for pybloomfiltermmap3 can include the bit array as a property of the BloomFilter object there, that would help a lot in use pybloomfiltermmap3 more broadly. (Also more explainable). 

Let me know if I need to file a feature request anywhere for this.

**Comment by mizvyt** [comment]
Nevermind my previous message, what I was really returning was just the pointer to the vector. I'm working on an actual implementation now.
